Adding an SV finder in FCCAnalyses
kunal2796/FCCAnalyses pull request #92
Opened 2022-06-20 17:19 UTC by kunal2796

adding an implementation of vertexing module from LCFIPlus into FCCAnalyses; new library VertexFinderLCFIPlus.h

2022-06-21 12:37 UTC, armin-ilg commented on analyzers/dataframe/VertexFinderLCFIPlus.cc
> +  int nJet = jets.size();
nJet is only used once, remove it here and add it in to for loop

2022-06-21 12:37 UTC, armin-ilg commented on analyzers/dataframe/VertexFinderLCFIPlus.cc
> +#include "TFile.h"
```suggestion
```

2022-06-21 12:39 UTC, armin-ilg commented on analyzers/dataframe/VertexFinderLCFIPlus.cc
> +#include "TString.h"
```suggestion
```

2022-06-21 12:40 UTC, armin-ilg commented on analyzers/dataframe/VertexFinderLCFIPlus.h
> +  VertexingUtils::FCCAnalysesV0 get_V0s_jet( ROOT::VecOps::RVec<edm4hep::ReconstructedParticleData> recoparticles,
add description here

2022-06-21 12:41 UTC, armin-ilg commented on analyzers/dataframe/VertexFinderLCFIPlus.cc
> +ROOT::VecOps::RVec<VertexingUtils::FCCAnalysesVertex> VertexFinderLCFIPlus::get_all_vertices(VertexingUtils::FCCAnalysesVertex PV,
Could be moved to VertexingUtils maybe? Functionality is not depending on LCFIPlus at all

2022-06-21 12:41 UTC, armin-ilg commented on analyzers/dataframe/VertexFinderLCFIPlus.h
> +#include "TVectorD.h"
Remove unnecessary includes: e.g ReconstructedParticle2MC.h, TVectorD.h, TMatrixDSym.h, TMath.h, TDecompChol.h, TMatrixD.h, VertexData.h, fastjet/JetDefinition.hh from VertexFinderLCFIPlus.h (or move them to the place where they are actually called if they are used deeper down)

2022-06-21 12:44 UTC, armin-ilg commented on analyzers/dataframe/VertexFinderLCFIPlus.cc
> +    // V0 rejection (tight)
So at the moment V0's can only be rejected tightly, right? Then I'd remove the "tight" completely, as it does not have meaning. Otherwise add the possiblity to have a loose rejection

2022-06-21 12:45 UTC, armin-ilg commented on analyzers/dataframe/VertexFinderLCFIPlus.cc
> +    // V0 rejection (tight)
Also the V0_rej should not be inside the V0rejection_tight, but outside, like this:
if(V0_rej):
ROOT::VecOps::RVec<edm4hep::TrackState> tracks_fin = V0rejection_tight(np_tracks, PV, V0_rej);
else:
ROOT::VecOps::RVec<edm4hep::TrackState> tracks_fin = np_tracks

2022-06-21 12:46 UTC, kunal2796 commented on analyzers/dataframe/VertexFinderLCFIPlus.cc
> +    // V0 rejection (tight)
ignore the V0 part for the moment. I'll make specific commits for changes there, I've already made one and am about to test it.

2022-06-21 12:47 UTC, armin-ilg commented on analyzers/dataframe/VertexFinderLCFIPlus.cc
> +    int i_nSV = i_result.size();
```suggestion
```

2022-06-21 12:48 UTC, armin-ilg commented on analyzers/dataframe/VertexFinderLCFIPlus.cc
> +    nSV_jet.push_back(i_nSV);
```suggestion
    nSV_jet.push_back(i_result.size());
```

2022-06-21 12:49 UTC, kunal2796 commented on analyzers/dataframe/VertexFinderLCFIPlus.h
> +#include "TVectorD.h"
except for fastjet one, you're right. I forgot to remove them during cleanup

2022-06-21 12:59 UTC, kunal2796 commented on analyzers/dataframe/VertexFinderLCFIPlus.cc
> +    // V0 rejection (tight)
also, currently, the "loose" rejection is done as in lines 218-220

2022-06-21 13:08 UTC, armin-ilg requested changes
It looks good! Much simpler than before. I think after these changes and fixing the struct seg fault issue, I'd send it to Clement and Emmanuel

2022-06-21 13:08 UTC, armin-ilg commented on analyzers/dataframe/VertexFinderLCFIPlus.cc
> +ROOT::VecOps::RVec<bool> VertexFinderLCFIPlus::isV0(ROOT::VecOps::RVec<edm4hep::TrackState> np_tracks,
Maybe instead of returning a boolean, it could return the pdgId, where 0 means that it is not a V0. Then you can massively simplify the get_V0 function, giving it this list of pdgId's instead of the booleans

2022-06-21 13:14 UTC, kunal2796 commented on analyzers/dataframe/VertexFinderLCFIPlus.cc
> +ROOT::VecOps::RVec<bool> VertexFinderLCFIPlus::isV0(ROOT::VecOps::RVec<edm4hep::TrackState> np_tracks,
having booleans makes V0s rejection incredibly easy. I've been thinking of ways to reduce things further, this sounds interesting. I'll look into it

2022-06-21 13:29 UTC, kunal2796 commented on analyzers/dataframe/VertexFinderLCFIPlus.cc
> +    // V0 rejection (tight)
> Also the V0_rej should not be inside the V0rejection_tight, but outside, like this: if(V0_rej): ROOT::VecOps::RVecedm4hep::TrackState tracks_fin = V0rejection_tight(np_tracks, PV, V0_rej); else: ROOT::VecOps::RVecedm4hep::TrackState tracks_fin = np_tracks

by passing V0_rej as an argument I move the "if-else" in the function since it's the same for all the functions. and V0_rej is to tell you if the user wants to perform V0 rejection or not, it has nothing to do with the tight/loose condition

2022-06-28 10:50 UTC, armin-ilg approved these changes
Looks good to me, thanks for the great comments in the code! :-)

2022-06-28 11:30 UTC, merged